In [1]:
import numpy as np
import pandas as pd
import warnings as wr
#Ignoring warnings
from sklearn.exceptions import UndefinedMetricWarning
wr.filterwarnings("ignore", category=UndefinedMetricWarning)

In [2]:
df=pd.read_csv('Colorectal_cancer_data.csv')

In [3]:
print(df.head(10))#Print all data of top 10 rows
print(df.shape)#Print the row and clumn count of the data
print(df.isna().sum())#Print all columns with empty data along with sum of empty data

   id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   
5   6                B      25       25         83   477       0.128   
6   7                M      16       26        120  1040       0.095   
7   8                M      15       18         90   578       0.119   
8   9                M      19       24         88   520       0.127   
9  10                M      25       11         84   476       0.119   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.26

In [4]:
df=df.dropna(axis=1)#Drop the column with empty data
df=df.drop(['id'],axis=1)

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()#Calling LabelEncoder
df.iloc[:,0]=labelencoder_X.fit_transform(df.iloc[:,0].values)#Encoding the values of diagnosis column to values

In [6]:
X=df.iloc[:,1:].values#Features of cancerous and non cancerous patients
Y=df.iloc[:,0].values#Whether patient has cancer or not

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)#Scaling X_train
X_test=sc.fit_transform(X_test)#Scaling X_test

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [10]:
#Function for  different models
def models(X_train,Y_train):

    #Logistic regression
    log=LogisticRegression(random_state=0)
    log.fit(X_train,Y_train)

    #Decision tree
    tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
    tree.fit(X_train,Y_train)

    #Random forest classifier
    forest=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    forest.fit(X_train,Y_train)

    #GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,Y_train)

    #Printing accuracy
    print("Logistic regression:",log.score(X_train,Y_train))
    print("Decision Tree:",tree.score(X_train,Y_train))
    print("Random Forest:",forest.score(X_train,Y_train))
    print("GaussianNB:",gnb.score(X_train,Y_train))
    return log,tree,forest,gnb

In [11]:
print("Accuracy")
model=models(X_train,Y_train)

Accuracy
Logistic regression: 0.9
Decision Tree: 1.0
Random Forest: 1.0
GaussianNB: 0.8333333333333334


In [12]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
for i in range(len(model)):
    print("\nModel:",i+1)
    print("Classification Report")
    print(classification_report(Y_test,model[i].predict(X_test)))
    print("Accuracy Score:",accuracy_score(Y_test,model[i].predict(X_test)))


Model: 1
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.60      0.75         5
           1       0.71      1.00      0.83         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10

Accuracy Score: 0.8

Model: 2
Classification Report
              precision    recall  f1-score   support

           0       0.33      0.20      0.25         5
           1       0.43      0.60      0.50         5

    accuracy                           0.40        10
   macro avg       0.38      0.40      0.38        10
weighted avg       0.38      0.40      0.38        10

Accuracy Score: 0.4

Model: 3
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.60      0.75         5
           1       0.71      1.00      0.83         5

    accuracy                           0.80   

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [15]:
def models(X_train,Y_train):

    #Logistic regression
    log=LogisticRegression(random_state=0)
    log.fit(X_train,Y_train)

    #Decision tree
    tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
    tree.fit(X_train,Y_train)

    #Random forest classifier
    forest=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    forest.fit(X_train,Y_train)

    #GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,Y_train)

    #Printing accuracy
    print("Logistic regression:",log.score(X_train,Y_train))
    print("Decision Tree:",tree.score(X_train,Y_train))
    print("Random Forest:",forest.score(X_train,Y_train))
    print("GaussianNB:",gnb.score(X_train,Y_train))
    return log,tree,forest,gnb

In [16]:
print("Accuracy")
model=models(X_train,Y_train)

Accuracy
Logistic regression: 0.8285714285714286
Decision Tree: 1.0
Random Forest: 0.9857142857142858
GaussianNB: 0.7428571428571429


c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
for i in range(len(model)):
    print("\nModel:",i+1)
    print("Classification Report")
    print(classification_report(Y_test,model[i].predict(X_test)))
    print("Accuracy Score:",accuracy_score(Y_test,model[i].predict(X_test)))


Model: 1
Classification Report
              precision    recall  f1-score   support

           0       0.88      0.78      0.82         9
           1       0.91      0.95      0.93        21

    accuracy                           0.90        30
   macro avg       0.89      0.87      0.88        30
weighted avg       0.90      0.90      0.90        30

Accuracy Score: 0.9

Model: 2
Classification Report
              precision    recall  f1-score   support

           0       0.41      0.78      0.54         9
           1       0.85      0.52      0.65        21

    accuracy                           0.60        30
   macro avg       0.63      0.65      0.59        30
weighted avg       0.72      0.60      0.61        30

Accuracy Score: 0.6

Model: 3
Classification Report
              precision    recall  f1-score   support

           0       0.64      0.78      0.70         9
           1       0.89      0.81      0.85        21

    accuracy                           0.80   

In [18]:
from sklearn.metrics import confusion_matrix

for i in range( len(model)):
  print('Model', i)
  cm = confusion_matrix(Y_test, model[i].predict(X_test))

  TP = cm[0][0]
  TN = cm[1][1]
  FN = cm[1][0]
  FP = cm[0][1]

  print(cm)
  print('Testing Accuracy = ',(TP + TN)/(TP + TN + FN + FP))
  print()

Model 0
[[ 7  2]
 [ 1 20]]
Testing Accuracy =  0.9

Model 1
[[ 7  2]
 [10 11]]
Testing Accuracy =  0.6

Model 2
[[ 7  2]
 [ 4 17]]
Testing Accuracy =  0.8

Model 3
[[ 8  1]
 [ 5 16]]
Testing Accuracy =  0.8

