In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Lung_cancer_data.csv')

In [3]:
print(df.head(10))#Print all data of top 10 rows
print(df.shape)#Print the row and clumn count of the data
print(df.isna().sum())#Print all columns with empty data along with sum of empty data

   class  attribute2  attribute3  attribute4  attribute5  attribute6  \
0      1           0           3           0         NaN           0   
1      1           0           3           3         1.0           0   
2      1           0           3           3         2.0           0   
3      1           0           2           3         2.0           1   
4      1           0           3           2         1.0           1   
5      1           0           3           3         2.0           0   
6      1           0           3           2         1.0           0   
7      1           0           2           2         1.0           0   
8      1           0           3           1         1.0           0   
9      2           0           2           3         2.0           0   

   attribute7  attribute8  attribute9  attribute10  ...  attribute48  \
0           2           2           2            1  ...            2   
1           3           1           3            1  ...        

In [4]:
df=df.dropna(axis=1)#Drop the column with empty data
print(df.iloc[:,0].value_counts())#Visualize the data of diagnosis column with y label counts
print(df.dtypes)#Data type of data in each column

2    13
3    10
1     9
Name: class, dtype: int64
class          int64
attribute2     int64
attribute3     int64
attribute4     int64
attribute6     int64
attribute7     int64
attribute8     int64
attribute9     int64
attribute10    int64
attribute11    int64
attribute12    int64
attribute13    int64
attribute14    int64
attribute15    int64
attribute16    int64
attribute17    int64
attribute18    int64
attribute19    int64
attribute20    int64
attribute21    int64
attribute22    int64
attribute23    int64
attribute24    int64
attribute25    int64
attribute26    int64
attribute27    int64
attribute28    int64
attribute29    int64
attribute30    int64
attribute31    int64
attribute32    int64
attribute33    int64
attribute34    int64
attribute35    int64
attribute36    int64
attribute37    int64
attribute38    int64
attribute40    int64
attribute41    int64
attribute42    int64
attribute43    int64
attribute44    int64
attribute45    int64
attribute46    int64
attribute47    int64
attri

In [5]:
X=df.iloc[:,1:].values#Features of cancerous and non cancerous patients
Y=df.iloc[:,0].values#Whether patient has cancer or not

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)#Scaling X_train
X_test=sc.fit_transform(X_test)#Scaling X_test

In [8]:
def models(X_train,Y_train):

    #Logistic regression
    from sklearn.linear_model import LogisticRegression
    log=LogisticRegression(random_state=0)
    log.fit(X_train,Y_train)

    #Decision tree
    from sklearn.tree import DecisionTreeClassifier
    tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
    tree.fit(X_train,Y_train)

    #Random forest classifier
    from sklearn.ensemble import RandomForestClassifier
    forest=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    forest.fit(X_train,Y_train)

    #GaussianNB
    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,Y_train)

    #Printing accuracy
    print("Logistic regression:",log.score(X_train,Y_train))
    print("Decision Tree:",tree.score(X_train,Y_train))
    print("Random Forest:",forest.score(X_train,Y_train))
    print("GaussianNB:",gnb.score(X_train,Y_train))
    return log,tree,forest,gnb

In [9]:
print("Accuracy")
model=models(X_train,Y_train)

Accuracy
Logistic regression: 1.0
Decision Tree: 1.0
Random Forest: 1.0
GaussianNB: 0.7083333333333334


In [10]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
for i in range(len(model)):
    print("\nModel",i+1)
    print("Classification Report")
    print(classification_report(Y_test,model[i].predict(X_test)))
    print("Accuracy Score:",accuracy_score(Y_test,model[i].predict(X_test)))


Model 1
Classification Report
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.50      0.50      0.50         4
           3       0.50      0.33      0.40         3

    accuracy                           0.38         8
   macro avg       0.33      0.28      0.30         8
weighted avg       0.44      0.38      0.40         8

Accuracy Score: 0.375

Model 2
Classification Report
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.75      0.75      0.75         4
           3       0.75      1.00      0.86         3

    accuracy                           0.75         8
   macro avg       0.50      0.58      0.54         8
weighted avg       0.66      0.75      0.70         8

Accuracy Score: 0.75

Model 3
Classification Report
              precision    recall  f1-score   support

           1       0.50      1.00      0.67    

In [11]:
from sklearn.metrics import confusion_matrix

for i in range( len(model)):
  print('Model', i)
  cm = confusion_matrix(Y_test, model[i].predict(X_test))

  TP = cm[0][0]
  TN = cm[1][1]
  FN = cm[1][0]
  FP = cm[0][1]

  print(cm)
  print('Testing Accuracy = ',(TP + TN)/(TP + TN + FN + FP))
  print()

Model 0
[[0 1 0]
 [1 2 1]
 [1 1 1]]
Testing Accuracy =  0.5

Model 1
[[0 1 0]
 [0 3 1]
 [0 0 3]]
Testing Accuracy =  0.75

Model 2
[[1 0 0]
 [1 1 2]
 [0 2 1]]
Testing Accuracy =  0.6666666666666666

Model 3
[[0 0 1]
 [1 3 0]
 [0 0 3]]
Testing Accuracy =  0.75

